-- Tạo DATABASE DOAN
CREATE DATABASE DoAN;
USE DoAN;

-- Tạo Table DOCGIA
CREATE TABLE DOCGIA (
		MADG INT AUTO_INCREMENT PRIMARY KEY,
        HOTEN VARCHAR(100) CHARACTER SET utf8mb4,
        EMAIL VARCHAR(100),
        SDT VARCHAR(10),
        NGSINH DATETIME,
        DIACHI VARCHAR(100) CHARACTER SET utf8mb4,
		NGDANGKY DATETIME
);

-- Tạo Table NHANVIEN
CREATE TABLE NHANVIEN (
	MANV INT AUTO_INCREMENT PRIMARY KEY,
	HOTEN VARCHAR(100) CHARACTER SET utf8mb4,
    NGSINH DATETIME,
    GIOITINH VARCHAR(4) CHARACTER SET utf8mb4,
    SDT VARCHAR(10),
    NGVAOLAM DATETIME,
    
    CONSTRAINT chk_GT_NhanVien CHECK (GIOITINH IN ('Nam', 'Nữ', 'Khác'))
);

-- Tạo Table THELOAI
CREATE TABLE THELOAI (
	MATL INT AUTO_INCREMENT PRIMARY KEY,
    TENTHELOAI VARCHAR(100) CHARACTER SET utf8mb4
);

-- Tạo Table TACGIA
CREATE TABLE TACGIA (
	MATG INT AUTO_INCREMENT PRIMARY KEY,
    TENTG VARCHAR(100) CHARACTER SET utf8mb4,
    NGSINH DATETIME,
    QUOCTICH VARCHAR(100) CHARACTER SET utf8mb4
);

-- Tạo Table NXB
CREATE TABLE NXB (
	MANXB INT AUTO_INCREMENT PRIMARY KEY,
    TENNXB VARCHAR(100) CHARACTER SET utf8mb4,
    EMAIL VARCHAR(100),
    SDT VARCHAR(10),
    DIACHI VARCHAR(100) CHARACTER SET utf8mb4
);

-- Tạo Table SACH
CREATE TABLE SACH (
	MASACH INT AUTO_INCREMENT PRIMARY KEY,
    TENSACH VARCHAR(100) CHARACTER SET utf8mb4,
    MATL INT,
    MATG INT,
    MANXB INT,
    NAMXB DATETIME,
    TAIBAN INT,
    VITRI VARCHAR(100) CHARACTER SET utf8mb4,
    TINHTRANG VARCHAR(100) CHARACTER SET utf8mb4,
    
    CONSTRAINT fk_Sach_TheLoai FOREIGN KEY (MATL) REFERENCES THELOAI(MATL),
    CONSTRAINT fk_Sach_TacGia FOREIGN KEY (MATG) REFERENCES TACGIA(MATG),
    CONSTRAINT fk_Sach_NXB FOREIGN KEY (MANXB) REFERENCES NXB(MANXB)
);

-- Tạo Table MUONSACH
CREATE TABLE MUONSACH (
	MAMUON INT AUTO_INCREMENT PRIMARY KEY,
    MADG INT,
    MANV INT,
    NGMUON DATETIME,
    NGDENHAN DATETIME,
    TRANGTHAI VARCHAR(20) CHARACTER SET utf8mb4,
    
    CONSTRAINT fk_MuonSach_DocGia FOREIGN KEY (MADG) REFERENCES DOCGIA(MADG),
    CONSTRAINT fk_MuonSach_NhanVien FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);

-- Tạo Table TRASACH
CREATE TABLE TRASACH (
	MATRA INT AUTO_INCREMENT PRIMARY KEY,
    MADG INT,
    MANV INT,
    NGTRA DATETIME,
    TRANGTHAI VARCHAR(20) CHARACTER SET utf8mb4,
    
    CONSTRAINT fk_TraSach_DocGia FOREIGN KEY (MADG) REFERENCES DOCGIA(MADG),
    CONSTRAINT fk_TraSach_NhanVien FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);

-- Tạo Table CTMUON
CREATE TABLE CTMUON (
	MACTMUON INT AUTO_INCREMENT PRIMARY KEY,
    MAMUON INT,
    MASACH INT,
    SOLUONG INT,
    TRANGTHAI VARCHAR(20) CHARACTER SET utf8mb4,
    
    CONSTRAINT fk_MuonSach_MuonSach FOREIGN KEY (MAMUON) REFERENCES MUONSACH(MAMUON),
    CONSTRAINT fk_CTMuon_Sach FOREIGN KEY (MASACH) REFERENCES SACH(MASACH)
);

-- Tạo Table CTTRA
CREATE TABLE CTTRA (
	MACTTRA INT AUTO_INCREMENT PRIMARY KEY,
    MATRA INT,
    MASACH INT,
    SOLUONG INT,
    TRANGTHAI VARCHAR(20) CHARACTER SET utf8mb4,
    
    CONSTRAINT fk_CTTra_TraSach FOREIGN KEY (MATRA) REFERENCES TRASACH(MATRA),
    CONSTRAINT fk_CTTra_Sach FOREIGN KEY (MASACH) REFERENCES SACH(MASACH)
);

-- Tạo Table PHIEUPHAT
CREATE TABLE PHIEUPHAT (
	MAPHAT INT AUTO_INCREMENT PRIMARY KEY,
    MAMUON INT,
    MANV INT, 
    LYDO VARCHAR(100) CHARACTER SET utf8mb4,
    NGLAP DATETIME,
    TRANGTHAI VARCHAR(20) CHARACTER SET utf8mb4,
    
    CONSTRAINT fk_PhieuPhat_MuonSach FOREIGN KEY (MAMUON) REFERENCES MUONSACH(MAMUON),
    CONSTRAINT fk_PhieuPhat_NhanVien FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);

-- Tạo Table HOADON
CREATE TABLE HOADON (
	MAHD INT AUTO_INCREMENT PRIMARY KEY,
    MADG INT,
    SOTIENTT INT,
    NGHD DATETIME,
    NGTT DATETIME,
    TRANGTHAI VARCHAR(20) CHARACTER SET utf8mb4,
    
    CONSTRAINT fk_HoaDon_DocGia FOREIGN KEY (MADG) REFERENCES DOCGIA(MADG)
);

-- Tạo Table CTHD
CREATE TABLE CTHD (
	MACTHD INT AUTO_INCREMENT PRIMARY KEY,
    MAHD INT,
    MASACH INT,
    SoLuong INT,
    SOTIEN INT,
    
    CONSTRAINT fk_CTHD_HoaDon FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD),
    CONSTRAINT fk_CTHD_MaSach FOREIGN KEY (MASACH) REFERENCES SACH(MASACH)
);


-- Tạo Index
-- Index trên DOCGIA
CREATE INDEX idx_DocGia_HoTen ON DOCGIA(HOTEN);

-- Index trên NHANVIEN
CREATE INDEX idx_NhanVien_HoTen ON NHANVIEN(HOTEN);
CREATE INDEX idx_NhanVien_SDT ON NHANVIEN(SDT);

-- Index trên THELOAI
CREATE INDEX idx_TheLoai_TenTL ON THELOAI(TENTHELOAI);

-- Index trên TACGIA
CREATE INDEX idx_TacGia_TenTG ON TACGIA(TENTG);

-- Index trên NXB
CREATE INDEX idx_NXB_TenNXB ON NXB(TENNXB);

-- Index trên SACH
CREATE INDEX idx_Sach_TenSach ON SACH(TENSACH);
CREATE INDEX idx_Sach_MaTL ON SACH(MATL);
CREATE INDEX idx_Sach_MaTG ON SACH(MATG);
CREATE INDEX idx_Sach_MaNXB ON SACH(MANXB);

-- Index trên MUONSACH
CREATE INDEX idx_MuonSach_MaDG ON MUONSACH(MADG);
CREATE INDEX idx_MuonSach_MaNV ON MUONSACH(MANV);
CREATE INDEX idx_MuonSach_NgDenHan ON MUONSACH(NGDENHAN);

-- Index trên TRASACH
CREATE INDEX idx_TraSach_MaDG ON TRASACH(MADG);
CREATE INDEX idx_TraSach_MaNV ON TRASACH(MANV);

-- Index trên CTMUON
CREATE INDEX idx_CTMuon_MaMuon ON CTMUON(MAMUON);
CREATE INDEX idx_CTMuon_MaSach ON CTMUON(MASACH);

-- Index trên CTTRA
CREATE INDEX idx_CTTra_MaMuon ON CTTRA(MATRA);
CREATE INDEX idx_CTMuon_MaSach ON CTTRA(MASACH);

-- Index trên PHIEUPHAT
CREATE INDEX idx_PhieuPhat_MaMuon ON PHIEUPHAT(MAMUON);
CREATE INDEX idx_PhieuPhat_MaNV ON PHIEUPHAT(MANV);

-- Index trên HOADON
CREATE INDEX idx_HoaDon_MaDG ON HOADON(MADG);

-- Index trên CTHD
CREATE INDEX idx_CTHD_MaHD ON CTHD(MAHD);
CREATE INDEX idx_CTHD_MaSach ON CTHD(MASACH);
